// Key figures that appear in more than one place on the site.
// Each fact has ONE canonical value and source. The data check fails if any
// place shows a different number, so when a figure changes, change it here
// first, run `node tools/check-data.cjs`, and it lists every place to update.
//
// place: [file, regex with one capture group for the number, rounding step]
//   file is 'home' (index.html) or 'notes' (notes/index.html)
//   the number is compared after rounding the canonical value to the step
//   (for example step 10 lets "2,060 GW" stand for 2,061 GW)
module.exports = [
  { name: 'BEHAVIOR-1K 2025 best task success, %', value: 12.4,
    source: 'https://robot-learning-collective.github.io/winning-behavior-1k-challenge',
    places: [['home', /finished only ([\d.]+) % of household chores/, 0.1],
             ['home', /\[([\d.]+),'now','BEHAVIOR-1K/, 0.1, v => 100 - v]] },
  { name: 'US interconnection queue, GW (end 2025)', value: 2061,
    source: 'https://emp.lbl.gov/publications/queued-2026-edition-characteristics',
    places: [['home', /About ([\d,]+) GW sits in the queue/, 10],
             ['home', />([\d,]+) GW<\/text>/, 10],
             ['home', /queue down 10 % in 2025 to ([\d,]+) GW/, 1],
             ['home', /with ([\d,]+) GW waiting/, 1]] },
  { name: 'US median wait to connect, months (2025)', value: 61,
    source: 'https://emp.lbl.gov/publications/queued-2026-edition-characteristics',
    places: [['home', /median US project waited (\d+) months/, 1],
             ['home', /waited a median (\d+) months/, 1],
             ['home', />(\d+) months<\/text>/, 1],
             ['home', /US median, built 2025 \((\d+) mo\)/, 1],
             ['home', /\[([\d.]+),'now','US median, built 2025/, 0.1, v => v / 12]] },
  { name: 'Share of queued capacity that gets built, %', value: 13,
    source: 'https://emp.lbl.gov/publications/queued-2026-edition-characteristics',
    places: [['home', /only (\d+) % of requested capacity/, 1],
             ['home', />(\d+) % built</, 1]] },
  { name: 'Blast furnace route, t CO₂ per t steel', value: 2.34,
    source: 'https://worldsteel.org/wider-sustainability/sustainability-indicators/',
    places: [['home', /\[([\d.]+),'now','World avg blast furnac/, 0.01],
             ['home', /about ([\d.]+) tonnes per tonne of steel/, 0.1],
             ['home', /≈ ([\d.]+) t CO₂ per t</, 0.1]] },
  { name: 'World average steel, t CO₂ per t', value: 1.92,
    source: 'https://worldsteel.org/wider-sustainability/sustainability-indicators/',
    places: [['home', /the world average is ([\d.]+) t CO₂ per tonne/, 0.01],
             ['home', /from today’s ([\d.]+) t world average/, 0.01]] },
  { name: 'Minimum energy to make iron from ore, GJ/t', value: 8.4,
    source: 'https://www.energy.gov/sites/prod/files/2015/08/f26/iron_and_steel_bandwidth_report_0.pdf',
    places: [['home', /minimum energy is ([\d.]+) GJ per tonne/, 0.1],
             ['home', /minimum energy ([\d.]+) GJ\/t/, 0.1],
             ['home', /Limit: ≈ ([\d.]+) GJ\/t to reduce ore/, 0.1],
             ['notes', /GJ\/t vs ([\d.]+) GJ\/t minimum/, 0.1]] },
  { name: 'World average steel energy, GJ/t', value: 20.95,
    source: 'https://worldsteel.org/wider-sustainability/sustainability-indicators/',
    places: [['home', /against a world average of (\d+)\./, 1],
             ['home', /world average (\d+)<\/text>/, 1],
             ['home', /to reduce ore \(vs ≈ (\d+) GJ/, 1],
             ['notes', /\(ironmaking\) – (\d+) GJ\/t/, 1]] },
  { name: 'NYC Second Ave Phase 2, $M per km', value: 2500,
    source: 'https://transitcosts.com/new-data/',
    places: [['home', /\[(\d+),'now','NYC 2nd Ave Ph\.2/, 1],
             ['home', /costs about ([\d,]+) million dollars in New York/, 1],
             ['home', />\$([\d,]+) M<\/text>/, 1]] },
  { name: 'Istanbul weighted average, $M per km', value: 126,
    source: 'https://transitcosts.com/new-data/',
    places: [['home', /\[(\d+),'now','Istanbul/, 1],
             ['home', /(\d+) million in Istanbul/, 1]] },
  { name: 'Logic gate energy vs Landauer, low end', value: 3e4,
    source: 'notes page: CMOS gate ≈ 0.1–1 fJ vs kT ln 2 = 2.9×10⁻²¹ J',
    places: [['home', /about (\d)×10⁴–\d×10⁵ times the Landauer/, 1, v => v / 1e4],
             ['notes', /\['Logic energy per operation','[^']*',([\de.]+),/, 1]] },
  { name: 'Logic gate energy vs Landauer, high end', value: 3e5,
    source: 'notes page: CMOS gate ≈ 0.1–1 fJ vs kT ln 2 = 2.9×10⁻²¹ J',
    places: [['home', /about \d×10⁴–(\d)×10⁵ times the Landauer/, 1, v => v / 1e5],
             ['notes', /\['Logic energy per operation','[^']*',[\de.]+,([\de.]+),/, 1]] },
];
